sonar.organization=225106138
sonar.projectKey=225106138_doubtfire-api
sonar.projectName=doubtfire-api-7.3HD
sonar.sources=app,lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io